import { homedir } from "node:os";
import { isAbsolute, parse, posix, resolve } from "node:path";
import {
  ANTIGRAVITY_RULE_FILE_CHAR_LIMIT, CODEWITH_FLATTENED_ADAPTER,
  CODEWITH_NATIVE_ADAPTER, CODEWITH_NATIVE_IMPORTS_ENV, RAW_STORE_ROOT_ENV,
  SESSION_LAYER_RANK, SESSION_RENDERER_OWNER_ID, SESSION_RENDER_MANAGED_MARKER,
  SESSION_RENDER_SCHEMA, SESSION_RENDER_TOOLS, SESSION_TOOL_ADAPTERS,
  normalizeSessionInstructionLayer, type IdentityExportShape,
  type OrderedSessionInstructionRule, type OrderedSessionInstructionSource,
  type SessionInstructionLayer, type SessionInstructionMerge, type SessionInstructionOwner,
  type SessionInstructionRule, type SessionInstructionSource, type SessionInstructionSourcePath,
  type SessionProfileRenderSelection, type SessionProviderConfig, type SessionRenderFile,
  type SessionRenderFileRole, type SessionRenderInput, type SessionRenderManifest,
  type SessionRenderMode, type SessionRenderPlan, type SessionRenderTargetKind,
  type SessionRenderTool, type SessionSkippedSource, type SessionTargetOwner,
  type SessionToolAdapter,
} from "./session-render-model.js";

import { defaultTargetHome, resolveSessionPath } from "./session-render-paths.js";

export function adapterFor(input: SessionRenderInput): SessionToolAdapter {
  if (input.tool !== "codewith") return SESSION_TOOL_ADAPTERS[input.tool];
  const gatedNativeImports =
    input.codewithNativeImports === true ||
    process.env[CODEWITH_NATIVE_IMPORTS_ENV] === "1" ||
    process.env[CODEWITH_NATIVE_IMPORTS_ENV] === "true";
  return gatedNativeImports ? CODEWITH_NATIVE_ADAPTER : CODEWITH_FLATTENED_ADAPTER;
}


export function resolveRenderTarget(input: SessionRenderInput): {
  targetHome: string;
  targetKind: SessionRenderTargetKind;
  blockers: string[];
} {
  if (input.tool === "cursor" || input.tool === "antigravity") {
    if (!input.projectRoot) {
      const label = input.tool === "cursor" ? "Cursor rules" : "Antigravity rules";
      const path = input.tool === "cursor" ? ".cursor/rules files" : ".agents/rules files";
      return {
        targetHome: defaultTargetHome(input.tool, input.profile, input.sessionId),
        targetKind: "blocked",
        blockers: [
          `${label} are project-scoped; pass --project-root (or projectRoot) before applying ${path}. --target-home is not treated as a repository root for ${input.tool}.`,
        ],
      };
    }
    return {
      targetHome: resolveSessionPath(input.projectRoot),
      targetKind: "project-root",
      blockers: [],
    };
  }

  return {
    targetHome: input.targetHome
      ? resolveSessionPath(input.targetHome)
      : defaultTargetHome(input.tool, input.profile, input.sessionId),
    targetKind: "session-home",
    blockers: [],
  };
}

export function resolveSessionTargetOwnership(input: Pick<SessionRenderInput, "tool" | "profile" | "projectRoot">, target: {
  targetHome: string;
  targetKind: SessionRenderTargetKind;
}): SessionTargetOwner {
  if (target.targetKind === "blocked") {
    return {
      kind: "blocked",
      tool: input.tool,
      profile: input.profile,
      targetHome: target.targetHome,
      projectRoot: input.projectRoot ? resolveSessionPath(input.projectRoot) : null,
      ownedBy: "open-configs",
      canonicalOwner: "instructions",
      writer: {
        id: SESSION_RENDERER_OWNER_ID,
        canonical: true,
        legacyAliases: ["open-configs"],
        scope: input.tool === "opencode" ? "managed-instruction-fields" : "managed-provider-files",
      },
      reason: "target resolution blocked before provider files can be owned",
    };
  }
  if (target.targetKind === "project-root") {
    return {
      kind: "project",
      tool: input.tool,
      profile: input.profile,
      targetHome: target.targetHome,
      projectRoot: target.targetHome,
      ownedBy: "open-configs",
      canonicalOwner: "instructions",
      writer: {
        id: SESSION_RENDERER_OWNER_ID,
        canonical: true,
        legacyAliases: ["open-configs"],
        scope: input.tool === "opencode" ? "managed-instruction-fields" : "managed-provider-files",
      },
      reason: "project-scoped provider files are generated in the explicit repository root",
    };
  }
  return {
    kind: "provider-profile",
    tool: input.tool,
    profile: input.profile,
    targetHome: target.targetHome,
    projectRoot: null,
    ownedBy: "open-configs",
    canonicalOwner: "instructions",
    writer: {
      id: SESSION_RENDERER_OWNER_ID,
      canonical: true,
      legacyAliases: ["open-configs"],
      scope: input.tool === "opencode" ? "managed-instruction-fields" : "managed-provider-files",
    },
    reason: "profile-scoped provider home is generated by Instructions from identity/config sources",
  };
}

