// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.
// Regenerate: bun run scripts/generate-sdk.ts

// @generated from OpenAPI by @hasna/contracts SDK generator — DO NOT EDIT.
// Source: Instructions V1 API 0.3.0

export interface Config { "id"?: string; "name"?: string; "slug"?: string; "kind"?: string; "category"?: string; "agent"?: string; "target_path"?: string | null; "outputs"?: Array<Record<string, unknown>>; "format"?: string; "content"?: string; "description"?: string | null; "tags"?: Array<string>; "is_template"?: boolean; "version"?: number; "created_at"?: string; "updated_at"?: string; "synced_at"?: string | null }

export interface Profile { "id"?: string; "name"?: string; "slug"?: string; "description"?: string | null; "selectors"?: Record<string, unknown>; "variables"?: Record<string, unknown>; "created_at"?: string; "updated_at"?: string }

export interface CreateConfigInput { "name": string; "category": string; "content": string; "kind"?: string; "agent"?: string; "target_path"?: string; "format"?: string; "description"?: string; "tags"?: Array<string>; "is_template"?: boolean }

export interface UpdateConfigInput { "name"?: string; "category"?: string; "agent"?: string; "content"?: string; "description"?: string; "tags"?: Array<string>; "is_template"?: boolean }

export interface CreateProfileInput { "name": string; "description"?: string; "selectors"?: Record<string, unknown>; "variables"?: Record<string, unknown> }

export interface InstructionsV1ClientOptions {
  /** Base URL, e.g. process.env.APP_API_URL. */
  baseUrl: string;
  /** API key, e.g. process.env.APP_API_KEY. Sent as the 'x-api-key' header. */
  apiKey?: string;
  /** Custom fetch (defaults to global fetch). */
  fetch?: typeof fetch;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
}

export class ApiError extends Error {
  constructor(readonly status: number, message: string, readonly body: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export class InstructionsV1Client {
  private readonly baseUrl: string;
  private readonly apiKey: string | undefined;
  private readonly fetchImpl: typeof fetch;
  private readonly baseHeaders: Record<string, string>;

  constructor(options: InstructionsV1ClientOptions) {
    if (!options.baseUrl) throw new Error("InstructionsV1Client requires a baseUrl.");
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.apiKey = options.apiKey;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.baseHeaders = options.headers ?? {};
  }

  private async request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    const url = new URL(this.baseUrl + path);
    if (opts.query) {
      for (const [key, value] of Object.entries(opts.query)) {
        if (value !== undefined && value !== null) url.searchParams.set(key, String(value));
      }
    }
    const headers: Record<string, string> = { Accept: "application/json", ...this.baseHeaders, ...(opts.init?.headers as Record<string, string> | undefined) };
    if (this.apiKey) headers["x-api-key"] = this.apiKey;
    let payload: BodyInit | undefined;
    if (opts.body !== undefined) {
      headers["Content-Type"] = "application/json";
      payload = JSON.stringify(opts.body);
    }
    const response = await this.fetchImpl(url.toString(), { ...opts.init, method, headers, body: payload });
    const text = await response.text();
    const data = text ? (() => { try { return JSON.parse(text); } catch { return text; } })() : undefined;
    if (!response.ok) {
      throw new ApiError(response.status, `${method} ${path} failed: ${response.status}`, data);
    }
    return data as T;
  }

    /** List configs */
    async listConfigs(query?: { "category"?: string; "agent"?: string; "kind"?: string; "search"?: string }, init?: RequestInit): Promise<{ "configs"?: Array<Config>; "count"?: number }> {
      return this.request("GET", `/v1/configs`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a config */
    async createConfig(body: CreateConfigInput, init?: RequestInit): Promise<{ "config"?: Config }> {
      return this.request("POST", `/v1/configs`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a config by id or slug */
    async getConfig(id: string, init?: RequestInit): Promise<{ "config"?: Config }> {
      return this.request("GET", `/v1/configs/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a config */
    async deleteConfig(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/configs/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a config */
    async updateConfig(id: string, body: UpdateConfigInput, init?: RequestInit): Promise<{ "config"?: Config }> {
      return this.request("PATCH", `/v1/configs/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List a config's version snapshots */
    async listSnapshots(id: string, init?: RequestInit): Promise<{ "snapshots"?: Array<Record<string, unknown>>; "count"?: number }> {
      return this.request("GET", `/v1/configs/${encodeURIComponent(String(id))}/snapshots`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Snapshot a config's current content */
    async createSnapshot(id: string, init?: RequestInit): Promise<{ "snapshot"?: Record<string, unknown> }> {
      return this.request("POST", `/v1/configs/${encodeURIComponent(String(id))}/snapshots`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** List profiles */
    async listProfiles(init?: RequestInit): Promise<{ "profiles"?: Array<Profile>; "count"?: number }> {
      return this.request("GET", `/v1/profiles`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Create a profile */
    async createProfile(body: CreateProfileInput, init?: RequestInit): Promise<{ "profile"?: Profile }> {
      return this.request("POST", `/v1/profiles`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a profile (with its configs) by id or slug */
    async getProfile(id: string, init?: RequestInit): Promise<{ "profile"?: Profile }> {
      return this.request("GET", `/v1/profiles/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a profile */
    async deleteProfile(id: string, init?: RequestInit): Promise<{ "deleted"?: boolean; "id"?: string }> {
      return this.request("DELETE", `/v1/profiles/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Aggregate config counts by category */
    async getStats(init?: RequestInit): Promise<{ "total"?: number }> {
      return this.request("GET", `/v1/stats`, {
        body: undefined,
        query: undefined,
        init,
      });
    }
}
